{
  description = "signal-ai-bot dev shell and native Signal services";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};

        # swag pinned to the version upstream's Dockerfile era uses; nixpkgs'
        # 1.16.6 fails to parse the project's @Success annotations.
        go-swag-1164 = pkgs.buildGoModule rec {
          pname = "go-swag";
          version = "1.16.4";
          src = pkgs.fetchFromGitHub {
            owner = "swaggo";
            repo = "swag";
            rev = "v${version}";
            hash = "sha256-wqBT7uan5XL51HHDGINRH9NTb1tybF44d/rWRxl6Lak=";
          };
          vendorHash = "sha256-6L5LzXtYjrA/YKmNEC/9dyiHpY/8gkH/CvW0JTo+Bwc=";
          subPackages = [ "cmd/swag" ];
          doCheck = false;
        };

        # Not in nixpkgs. The docs package main.go imports is generated by
        # swag at build time (mirrors upstream's Dockerfile). jsonrpc2-helper
        # (scripts/) is intentionally not built — scripts/signal_api.py
        # replicates it (jsonrpc2.yml + signal-cli daemon --tcp).
        signal-cli-rest-api = pkgs.buildGoModule rec {
          pname = "signal-cli-rest-api";
          version = "0.100";
          src = pkgs.fetchFromGitHub {
            owner = "bbernhard";
            repo = "signal-cli-rest-api";
            rev = version;
            hash = "sha256-o6CNDVkd+Rofj+oFIUM1cuEKhHndZb796YbrvTecq4E=";
          };
          modRoot = "src";
          vendorHash = "sha256-HOX1xXtUP+47+PIDJ/gWYe6PSOw3b/aiTqnwu+rSQt4=";
          subPackages = [ "." ];
          nativeBuildInputs = [ go-swag-1164 ];
          preBuild = ''
            swag init --requiredByDefault --outputTypes "go,json"
          '';
          # Don't run swag while vendoring go modules.
          overrideModAttrs = old: { preBuild = null; };
        };

        # One bin/ with signal-cli (JRE + arch-correct libsignal handled by
        # nixpkgs) and signal-cli-rest-api; scripts/signal_api.py points here
        # via `nix build .#signal-services -o .nix-services`.
        signal-services = pkgs.symlinkJoin {
          name = "signal-services";
          paths = [ pkgs.signal-cli signal-cli-rest-api ];
        };
      in
      {
        packages = {
          inherit signal-cli-rest-api signal-services;
          default = signal-services;
        };

        # M4 will add pkgs.playwright-driver.browsers here; the pip `playwright`
        # pin in requirements.in must match nixpkgs' playwright-driver version —
        # bump them together. The systemd unit then exports
        # PLAYWRIGHT_BROWSERS_PATH and PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS.
        devShells.default = pkgs.mkShell {
          packages = with pkgs; [
            bazelisk
            gallery-dl
          ];
          inputsFrom = [ ];
        };
      });
}
