load("@rules_python//python:defs.bzl", "py_test")

[
    py_test(
        name = name,
        srcs = [name + ".py"],
        deps = [
            "//sigbot:sigbot_lib",
            "@sigbot_pypi//pytest",
        ],
    )
    for name in [
        "sigbot_store_test",
        "sigbot_listener_test",
        "sigbot_agent_test",
        "sigbot_api_test",
        "sigbot_config_test",
    ]
]

py_test(
    name = "sigbot_client_test",
    srcs = ["sigbot_client_test.py"],
    deps = [
        "//client:sigbot_client_lib",
        "@sigbot_pypi//pytest",
    ],
)
