load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "smoke_test",
    srcs = ["smoke_test.py"],
    deps = [
        "//finder:finder_lib",
        "@pypi//pytest",
    ],
)

py_test(
    name = "store_test",
    srcs = ["store_test.py"],
    deps = [
        "//finder:finder_lib",
        "@pypi//pytest",
    ],
)
