#!/usr/bin/env bash
# sigbot installer: pulls the prebuilt images, commissions the instance
# (config + secrets), and starts signal-cli-rest-api + sigbot under docker
# compose. Safe to re-run: commissioning is skipped if config already exists.
#
#   curl -fsSL https://raw.githubusercontent.com/fughilli/sigbot/master/deploy/install.sh | bash
#
# Env overrides: SIGBOT_HOME (default ~/sigbot), SIGBOT_IMAGE, SIGNAL_IMAGE.
set -euo pipefail

SIGBOT_HOME="${SIGBOT_HOME:-$HOME/sigbot}"
SIGBOT_IMAGE="${SIGBOT_IMAGE:-ghcr.io/fughilli/sigbot:latest}"
SIGNAL_IMAGE="${SIGNAL_IMAGE:-bbernhard/signal-cli-rest-api:0.100}"

say()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

command -v docker >/dev/null || fail "docker is required (https://docs.docker.com/engine/install/)"
docker compose version >/dev/null 2>&1 || fail "docker compose v2 is required"

mkdir -p "$SIGBOT_HOME/data/signal-cli"
cd "$SIGBOT_HOME"

# -- commissioning: config + secrets, generated once ---------------------------

if [[ -f data/sigbot.yaml && -f .env ]]; then
  say "already commissioned ($SIGBOT_HOME) — keeping existing config/secrets"
else
  say "commissioning sigbot in $SIGBOT_HOME"
  # `curl | bash` leaves stdin on the pipe — prompt on the terminal instead
  if [[ ! -t 0 ]]; then
    [[ -r /dev/tty ]] || fail "no terminal for prompts; run the script directly"
    exec < /dev/tty
  fi
  read -rp "Bot Signal number (E.164, e.g. +15551234567): " BOT_NUMBER
  [[ "$BOT_NUMBER" =~ ^\+[0-9]{7,15}$ ]] || fail "that doesn't look like an E.164 number"
  read -rp "Bot display name [Botsy]: " BOT_NAME; BOT_NAME="${BOT_NAME:-Botsy}"
  read -rp "Anthropic API key (sk-ant-...): " ANTHROPIC_KEY
  [[ -n "$ANTHROPIC_KEY" ]] || fail "an Anthropic API key is required"
  read -rp "Dashboard admin username [admin]: " ADMIN_USER; ADMIN_USER="${ADMIN_USER:-admin}"
  read -rsp "Dashboard admin password [generate]: " ADMIN_PASS; echo
  if [[ -z "$ADMIN_PASS" ]]; then
    ADMIN_PASS="$(head -c 12 /dev/urandom | base64 | tr -d '/+=' )"
    GENERATED=1
  fi

  cat > data/sigbot.yaml <<EOF
# sigbot static config (commissioned $(date -u +%F) by install.sh).
# Services (group personas), API keys, and further admins are managed in the
# dashboard at http://<this-host>:8100/ — not in this file.
signal:
  api_url: http://signal-api:8080
  bot_number: "$BOT_NUMBER"
bot_name: $BOT_NAME
db_path: sigbot.db
anthropic_api_key_env: ANTHROPIC_API_KEY
default_model: claude-sonnet-4-6
api:
  host: 0.0.0.0
  port: 8100
EOF

  cat > .env <<EOF
# sigbot secrets (chmod 600; never commit). Regenerate the admin password by
# deleting the admin row or via the in-container CLI:
#   docker compose exec sigbot /sigbot/admin --config /data/sigbot.yaml set-password $ADMIN_USER
ANTHROPIC_API_KEY=$ANTHROPIC_KEY
SIGBOT_ADMIN_USER=$ADMIN_USER
SIGBOT_ADMIN_PASSWORD=$ADMIN_PASS
EOF
  chmod 600 .env
  say "wrote data/sigbot.yaml and .env (secrets, mode 600)"
  [[ -n "${GENERATED:-}" ]] && say "generated dashboard password for '$ADMIN_USER': $ADMIN_PASS (stored in .env)"
fi

# -- compose file (regenerated each run; config lives in sigbot.yaml/.env) -----

cat > docker-compose.yml <<EOF
# Generated by install.sh — edits belong in data/sigbot.yaml and .env.
services:
  signal-api:
    image: $SIGNAL_IMAGE
    restart: unless-stopped
    environment:
      - MODE=json-rpc
    ports:
      - "127.0.0.1:8080:8080"   # account provisioning + debugging only
    volumes:
      - ./data/signal-cli:/home/.local/share/signal-cli
  sigbot:
    image: $SIGBOT_IMAGE
    restart: unless-stopped
    depends_on:
      - signal-api
    env_file: .env
    ports:
      - "8100:8100"             # service API + admin dashboard
    volumes:
      - ./data:/data
EOF

say "pulling images"
docker compose pull
say "starting services"
docker compose up -d

cat <<EOF

sigbot is up.

  Dashboard:    http://$(hostname -I 2>/dev/null | awk '{print $1}' || echo 127.0.0.1):8100/  (login: see $SIGBOT_HOME/.env)
  Service API:  same port, /api/v1/* with a minted bearer key

If this Signal number isn't provisioned yet (fresh data/signal-cli), do ONE of:
  - Register it as a new account (needs an SMS/voice-capable number + captcha):
      https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/EXAMPLES.md#register-a-number
    (the API is on http://127.0.0.1:8080)
  - Link it as a device of an existing account: open
      http://127.0.0.1:8080/v1/qrcodelink?device_name=sigbot
    and scan the QR from Signal > Settings > Linked Devices.
Then restart sigbot to pick it up:  docker compose restart sigbot

Next: add the bot's number to a Signal group, open the dashboard, register the
group as a service (persona + reply policy), and mint API keys for it.
EOF
